#!/bin/bash

#SBATCH --nodes=1
#SBATCH --job-name=AdaKMS_12_920
#SBATCH --cpus-per-task=10
#SBATCH --time=120:00:00
#SBATCH --mem=16G
#SBATCH --array=1-100

module load python/3.9
for src in ./bin0628/*.bin; do
  for i in {1..10}; do
    srun python3 Clusters_ADAKMS_bootstrap.py \
      src:${src} dataset:920 alphabet:24 repeats:1 \
      seed:${SLURM_ARRAY_TASK_ID}013370${i} &
  done
  wait
done
